config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts
  resources :tags

end

app/models/pair.rb
class Pair < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	
	has_many :pairs, dependent: :destroy
  	has_many :tags, through: :pairs

end

app/models/tag.rb
class Tag < ActiveRecord::Base

	has_many :pairs, dependent: :destroy
	has_many :posts, through: :pairs

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_tags, only: [:show, :edit, :update, :destroy]

  def index
	@posts = Post.all
  end

  def new
  	@post = Post.new
  	@tags = Tag.all
  end

  def create
  	@post = Post.create(post_params)
  	if @post.save
  		redirect_to posts_path, notice: 'Post successfully added'
  	else
  		render :new
  	end
  end

def edit
  end

def update
	@post.update_attributes(post_params)
	if @post.save
		redirect_to posts_path, notice: 'Post successfully updated'
	else
		render :edit
	end
end

  def show
  end

  def destroy
  	@post.destroy
  	redirect_to posts_path
  end

  private
  	  def post_params
  	  	params.require(:post).permit(:title, :author, :content, :tag_ids => [])
  	  end
	  def set_post
	  	@post = Post.find_by(id: params[:id])
	  end
	  def set_tags
	  	@tags = Tag.all
	  end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :set_posts, only: [:show, :edit, :update, :destroy]

  def index
  	@tags = Tag.all
  end

  def new
  	@tag = Tag.new
  	@posts = Post.all
  end

  def create
  	@tag = Tag.create(tag_params)
  	if @tag.save
  		redirect_to tags_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	@tag.update_attributes(tag_params)
  	if @tag.save
  		redirect_to tags_path
  	else
  		render :edit
  	end
  end

  def show
  end

  def destroy
  	@tag.destroy
  	redirect_to tags_path
  end

  private
	  def tag_params
		params.require(:tag).permit(:name, :post_ids => [])	  	
	  end

	  def set_tag
	  	@tag = Tag.find_by(id: params[:id])
	  end

	  def set_posts
	  	@posts = Post.all
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://bootswatch.com/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <script src="https://bootswatch.com/assets/js/bootswatch.js"></script>
  <script src="https://ssl.google-analytics.com/ga.js"></script>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>

</head>
<body>

	<div class="bs-component">
	              <nav class="navbar navbar-inverse">
	                <div class="container-fluid">
	                  <div class="navbar-header">
	                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
	                      <span class="sr-only">Toggle navigation</span>
	                      <span class="icon-bar"></span>
	                      <span class="icon-bar"></span>
	                      <span class="icon-bar"></span>
	                    </button>
	                    <a class="navbar-brand" href="/">RailsBlog</a>
	                  </div>

	                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
	                    <ul class="nav navbar-nav">
	                      <li><a href="/posts/new">Add a Post<span class="sr-only">(current)</span></a></li>
	                      <li><a href="/tags">Tags Page</a></li>
	                      <li class="dropdown">
	                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">User Info <span class="caret"></span></a>
	                        <ul class="dropdown-menu" role="menu">
	                          <li><a href="#">Action</a></li>
	                          <li><a href="#">Another action</a></li>
	                          <li><a href="#">Something else here</a></li>
	                          <li class="divider"></li>
	                          <li><a href="#">Separated link</a></li>
	                          <li class="divider"></li>
	                          <li><a href="#">One more separated link</a></li>
	                        </ul>
	                      </li>
	                    </ul>
	                    <form class="navbar-form navbar-left" role="search">
	                      <div class="form-group">
	                        <input class="form-control" placeholder="Search" type="text">
	                      </div>
	                      <button type="submit" class="btn btn-default">Submit</button>
	                    </form>
	                    <ul class="nav navbar-nav navbar-right">
	                      <li><a href="#">Link</a></li>
	                    </ul>
	                  </div>
	                </div>
	              </nav>
	            <div style="display: none;" id="source-button" class="btn btn-primary btn-xs">&lt; &gt;</div>
    </div>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |error| %>
   
    <p class="text-danger">
      <%= error%>
    </p>
  <% end %>
<% end %>


<%= form_for @post do |f| %>
    <%= f.label "Title" %>
    <%= f.text_field :title %><br />
    <%= f.label "Author" %>
    <%= f.text_field :author %><br />
    <%= f.label "Content" %>
    <%= f.text_field :content %><br />
    
    
    <%= f.collection_check_boxes(:tag_ids, @tags, :id, :name) do |b| %>
            <%= b.check_box %>
            <%= b.label %>
        <% end %>
    <%= f.submit "GO!" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

<%= render 'form'  %>

	<%= link_to 'Delete this post', post_path, method: :delete %>

app/views/posts/index.html.erb
<div class="allPosts">
<% @posts.each do |post| %>
	<div class="panel panel-primary aPost">
	                <div class="panel-heading">
	                  <h1 style="float: left; margin-left: 20px;" class="panel-title aPostTitle">
	                  	<%= link_to post.title, post_path(post.id) %>
	                  </h1>
	                  <span style="float: right; margin-top: 12px" class="label label-info" data-toggle="tooltip" data-placement="right" title="<%= post.author %>"><%= post.user.name %><span class="badge"><%= post.user.posts.length%></span></span>
	                </div>
	                <div class="panel-body aPostBody">
	            
	                	<!-- <span style="float: right; margin-top: 0px" class="label label-info" data-toggle="tooltip" data-placement="left" title="<%= post.author %>"><%= post.user.name %><span class="badge"><%= post.user.posts.length%></span></span> -->

						<p class="post-body"><%= post.content %></p>
						<p><%= link_to "Edit this Post", edit_post_path(post.id) %></p>

						<div class="panel panel-info">
						                <div class="panel-heading">
						                  <h3 class="panel-title">Tags:</h3>
						                </div>
						                <div class="panel-body">
						                	<% post.tags.each do |tag| %>
						        				<%= tag.name %>          
						                	<% end %>
						                </div>
						                
		              	</div>
		  			</div>
	</div>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= render 'form'  %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

	<%= link_to "Home", posts_path %>

	<div>
		<p><%= @post.title %></p>
		<p>By: <%= @post.author %></p>
		<p>Content: <%= @post.content %></p>
		<p><%= link_to "Edit this post", edit_post_path(@post.id) %></p>
		<p>
			Tags:
			<% @post.tags.each do |tag| %>
				<%= tag.name %>
			<% end %>
		</p>
	</div>

app/views/tags/_form.html.erb
<% if @tag.errors.any? %>
  <% @tag.errors.full_messages.each do |error| %>
   
    <p class="text-danger">
      <%= error%>
    </p>
  <% end %>
<% end %>


<%= form_for @tag do |f| %>
    <%= f.label "Name" %>
    <%= f.text_field :name %><br />
    
    <%= f.collection_check_boxes(:post_ids, @posts, :id, :title) do |b| %>
            <%= b.check_box %>
            <%= b.label %>
        <% end %>
    <%= f.submit "GO!" %>
<% end %>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<p>Find me in app/views/tags/edit.html.erb</p>

<%= render 'form'  %>

	<%= link_to 'Delete this tag', tag_path, method: :delete %>

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>
	<%= link_to "Home", posts_path %>
	<%= link_to "Add a Tag", new_tag_path %>

<% @tags.each do |tag| %>
	<div>
		<p>Tag name: <%= link_to tag.name, tag_path(tag.id) %></p>
		<p><%= link_to "See More", tag_path(tag.id) %></p>
		<p><%= link_to "Edit this Tag", edit_tag_path(tag.id) %></p>
		<p>
			Post(s):
			<% tag.posts.each do |post| %>
				<p>
					<%= link_to post.title, post_path(post.id) %>
					By: <%= post.author %>
				</p>
			<% end %>
		</p>
	</div>
<% end %>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

<%= render 'form'  %>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
	<%= link_to "Home", posts_path %>

<div>
	<p>Tag name:<%= @tag.name %></p>
	<p><%= link_to "See More", tag_path(@tag.id) %></p>
	<p><%= link_to "Edit this Tag", edit_tag_path(@tag.id) %></p>
	<p>
		Post(s):
		<% @tag.posts.each do |post| %>
			<p>
				<%= link_to post.title, post_path(post.id) %>
				By: <%= post.author %>
			</p>
		<% end %>
	</p>
</div>